// Auto-generated by `mcp__supabase__generate_typescript_types`.
// Regenerate from the current schema with:
//   npx supabase gen types typescript --project-id ettxkixkxrzchbnohgfm
// Used by Edge Functions (Deno) and any future TS admin tooling.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      coin_embeddings: {
        Row: {
          created_at: string
          embedding: number[]
          eurio_id: string
          model_version: string
        }
        Insert: {
          created_at?: string
          embedding: number[]
          eurio_id: string
          model_version: string
        }
        Update: {
          created_at?: string
          embedding?: number[]
          eurio_id?: string
          model_version?: string
        }
        Relationships: [
          {
            foreignKeyName: "coin_embeddings_eurio_id_fkey"
            columns: ["eurio_id"]
            isOneToOne: true
            referencedRelation: "coins"
            referencedColumns: ["eurio_id"]
          },
        ]
      }
      coins: {
        Row: {
          collector_only: boolean
          country: string
          cross_refs: Json
          currency: string
          design_description: string | null
          eurio_id: string
          face_value: number
          first_seen: string
          images: Json
          is_commemorative: boolean
          last_updated: string
          national_variants: Json | null
          needs_review: boolean
          review_reason: string | null
          sources_used: string[]
          theme: string | null
          year: number
        }
        Insert: {
          collector_only?: boolean
          country: string
          cross_refs?: Json
          currency?: string
          design_description?: string | null
          eurio_id: string
          face_value: number
          first_seen?: string
          images?: Json
          is_commemorative?: boolean
          last_updated?: string
          national_variants?: Json | null
          needs_review?: boolean
          review_reason?: string | null
          sources_used?: string[]
          theme?: string | null
          year: number
        }
        Update: {
          collector_only?: boolean
          country?: string
          cross_refs?: Json
          currency?: string
          design_description?: string | null
          eurio_id?: string
          face_value?: number
          first_seen?: string
          images?: Json
          is_commemorative?: boolean
          last_updated?: string
          national_variants?: Json | null
          needs_review?: boolean
          review_reason?: string | null
          sources_used?: string[]
          theme?: string | null
          year?: number
        }
        Relationships: []
      }
      matching_decisions: {
        Row: {
          confidence: number | null
          decided_at: string
          eurio_id: string | null
          id: number
          method: string
          reviewer_notes: string | null
          runner_up: string | null
          source: string
          source_native_id: string | null
        }
        Insert: {
          confidence?: number | null
          decided_at?: string
          eurio_id?: string | null
          id?: number
          method: string
          reviewer_notes?: string | null
          runner_up?: string | null
          source: string
          source_native_id?: string | null
        }
        Update: {
          confidence?: number | null
          decided_at?: string
          eurio_id?: string | null
          id?: number
          method?: string
          reviewer_notes?: string | null
          runner_up?: string | null
          source?: string
          source_native_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "matching_decisions_eurio_id_fkey"
            columns: ["eurio_id"]
            isOneToOne: false
            referencedRelation: "coins"
            referencedColumns: ["eurio_id"]
          },
        ]
      }
      review_queue: {
        Row: {
          candidates: Json | null
          created_at: string
          id: number
          raw_payload: Json
          reason: string
          resolution: Json | null
          resolved: boolean
          source: string
          source_native_id: string | null
        }
        Insert: {
          candidates?: Json | null
          created_at?: string
          id?: number
          raw_payload: Json
          reason: string
          resolution?: Json | null
          resolved?: boolean
          source: string
          source_native_id?: string | null
        }
        Update: {
          candidates?: Json | null
          created_at?: string
          id?: number
          raw_payload?: Json
          reason?: string
          resolution?: Json | null
          resolved?: boolean
          source?: string
          source_native_id?: string | null
        }
        Relationships: []
      }
      source_observations: {
        Row: {
          eurio_id: string
          id: number
          observation_type: string
          payload: Json
          sampled_at: string
          source: string
          source_native_id: string | null
        }
        Insert: {
          eurio_id: string
          id?: number
          observation_type: string
          payload: Json
          sampled_at?: string
          source: string
          source_native_id?: string | null
        }
        Update: {
          eurio_id?: string
          id?: number
          observation_type?: string
          payload?: Json
          sampled_at?: string
          source?: string
          source_native_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "source_observations_eurio_id_fkey"
            columns: ["eurio_id"]
            isOneToOne: false
            referencedRelation: "coins"
            referencedColumns: ["eurio_id"]
          },
        ]
      }
      user_collections: {
        Row: {
          added_at: string
          eurio_id: string
          id: number
          notes: string | null
          quality: string | null
          scan_image_url: string | null
          user_id: string
          value_at_addition: number | null
        }
        Insert: {
          added_at?: string
          eurio_id: string
          id?: number
          notes?: string | null
          quality?: string | null
          scan_image_url?: string | null
          user_id: string
          value_at_addition?: number | null
        }
        Update: {
          added_at?: string
          eurio_id?: string
          id?: number
          notes?: string | null
          quality?: string | null
          scan_image_url?: string | null
          user_id?: string
          value_at_addition?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "user_collections_eurio_id_fkey"
            columns: ["eurio_id"]
            isOneToOne: false
            referencedRelation: "coins"
            referencedColumns: ["eurio_id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
