"""Builder for the coin_price table.

Produces rows for two kinds of price data:
- 'market'    : from coin_market_quotes (eBay, Numista, LMDLP)
- 'catalogue' : from mint_release_prices aggregated per (eurio_id, grade_eurio)

Target Supabase columns (id is identity-generated by Postgres — omitted):
    eurio_id, kind, grade, p_low, p_mid, p_high, currency, source, buy_url,
    sampled_at

All prices in eurio.db are stored as EUR floats; we convert to integer cents
via round(x * 100).
"""

from __future__ import annotations

import json
import sqlite3
import statistics
from typing import Any


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_LMDLP_UNC_RAW: frozenset[str] = frozenset(
    {"UNC", "BU FDC", "BE Proof", "BE Polissage inversé"}
)
_VALID_GRADES: frozenset[str] = frozenset({"UNC", "TTB", "TB"})


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _cents(value: float | None) -> int | None:
    """Convert a EUR float to integer cents, or None if value is None."""
    if value is None:
        return None
    return round(value * 100)


def _extract_permalink(raw_payload_json: str | None) -> str | None:
    """Return the 'permalink' field from a JSON payload, or None."""
    if not raw_payload_json:
        return None
    try:
        payload: Any = json.loads(raw_payload_json)
        if isinstance(payload, dict):
            permalink = payload.get("permalink")
            return str(permalink) if permalink is not None else None
    except (json.JSONDecodeError, TypeError):
        pass
    return None


# ---------------------------------------------------------------------------
# Market builder
# ---------------------------------------------------------------------------

def _build_market_rows(con: sqlite3.Connection) -> list[dict]:
    """Return one row per (eurio_id, grade) — most recent quote wins.

    LMDLP grades: map condition_raw to 'UNC' when it is one of the known
    premium conditions; skip rows where condition_raw='unknown'.
    Other sources: use condition_normalized when in {UNC, TTB, TB}.
    """
    # Fetch all candidate rows ordered by recency so the first seen per key
    # is the most recent.  Using period_end then fetched_at as tiebreakers.
    sql = """
        SELECT
            eurio_id,
            source,
            condition_raw,
            condition_normalized,
            p10,
            p50,
            p90,
            currency,
            period_end,
            raw_payload_json
        FROM coin_market_quotes
        WHERE eurio_id IN (SELECT eurio_id FROM coins)
        ORDER BY period_end DESC, fetched_at DESC
    """
    seen: dict[tuple[str, str], dict] = {}

    for row in con.execute(sql):
        eurio_id: str = row["eurio_id"]
        source: str = row["source"]
        condition_raw: str | None = row["condition_raw"]
        condition_normalized: str = row["condition_normalized"]

        # Resolve grade
        if source == "lmdlp":
            if condition_raw in _LMDLP_UNC_RAW:
                grade = "UNC"
            else:
                # unknown or unmappable — skip
                continue
        else:
            if condition_normalized in _VALID_GRADES:
                grade = condition_normalized
            else:
                continue

        key = (eurio_id, grade)
        if key in seen:
            # Already recorded a more recent quote for this (eurio_id, grade)
            continue

        buy_url: str | None = None
        if source == "lmdlp":
            buy_url = _extract_permalink(row["raw_payload_json"])

        seen[key] = {
            "eurio_id": eurio_id,
            "kind": "market",
            "grade": grade,
            "p_low": _cents(row["p10"]),
            "p_mid": _cents(row["p50"]),
            "p_high": _cents(row["p90"]),
            "currency": row["currency"],
            "source": source,
            "buy_url": buy_url,
            "sampled_at": row["period_end"],
        }

    return list(seen.values())


# ---------------------------------------------------------------------------
# Catalogue builder
# ---------------------------------------------------------------------------

def _build_catalogue_rows(con: sqlite3.Connection) -> list[dict]:
    """Return one row per (eurio_id, grade_eurio) aggregated across releases.

    p_low  = round(min(price) * 100)
    p_mid  = round(median(price) * 100)
    p_high = round(max(price) * 100)
    currency / source : taken from the most recently fetched row for the group
    sampled_at        : max(fetched_at) for the group
    """
    sql = """
        SELECT
            cmr.parent_type_id  AS eurio_id,
            mrp.grade_eurio,
            mrp.price,
            mrp.currency,
            mrp.source,
            mrp.fetched_at
        FROM mint_release_prices mrp
        JOIN coin_mint_releases cmr ON mrp.mint_release_id = cmr.id
        WHERE mrp.grade_eurio IN ('UNC', 'TTB', 'TB')
          AND mrp.price IS NOT NULL
          AND cmr.parent_type_id IN (SELECT eurio_id FROM coins)
        ORDER BY cmr.parent_type_id, mrp.grade_eurio, mrp.fetched_at DESC
    """

    # Accumulate prices and metadata per (eurio_id, grade)
    groups: dict[tuple[str, str], dict] = {}

    for row in con.execute(sql):
        eurio_id: str = row["eurio_id"]
        grade: str = row["grade_eurio"]
        price: float = row["price"]
        key = (eurio_id, grade)

        if key not in groups:
            groups[key] = {
                "prices": [],
                "currency": row["currency"],
                "source": row["source"],
                "sampled_at": row["fetched_at"],
            }

        groups[key]["prices"].append(price)
        # Keep the latest fetched_at (rows are ordered DESC so first is latest)
        if row["fetched_at"] > groups[key]["sampled_at"]:
            groups[key]["sampled_at"] = row["fetched_at"]

    rows: list[dict] = []
    for (eurio_id, grade), g in groups.items():
        prices = sorted(g["prices"])
        rows.append({
            "eurio_id": eurio_id,
            "kind": "catalogue",
            "grade": grade,
            "p_low": _cents(min(prices)),
            "p_mid": _cents(statistics.median(prices)),
            "p_high": _cents(max(prices)),
            "currency": g["currency"],
            "source": g["source"],
            "buy_url": None,
            "sampled_at": g["sampled_at"],
        })

    return rows


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def build_coin_price(con: sqlite3.Connection) -> list[dict]:
    """Build all coin_price rows (market + catalogue).

    Each dict has exactly the target Supabase columns:
        eurio_id, kind, grade, p_low, p_mid, p_high, currency, source,
        buy_url, sampled_at

    The Postgres identity column `id` is intentionally omitted.
    """
    market_rows = _build_market_rows(con)
    catalogue_rows = _build_catalogue_rows(con)
    return market_rows + catalogue_rows
