"""Builders for relational/lookup tables.

Tables covered:
    mint, coin_mint_release, coin_credit, coin_topic, design_group

Each builder is a pure function (sqlite3.Connection) -> list[dict] whose keys
are exactly the target Supabase column names.  No network, no side effects.
"""

from __future__ import annotations

import sqlite3
from typing import Any


# ---------------------------------------------------------------------------
# build_design_group
# ---------------------------------------------------------------------------

def build_design_group(con: sqlite3.Connection) -> list[dict[str, Any]]:
    """Source: design_groups (5 rows).

    Target columns: id, designation, designation_i18n_json
    designation_i18n_json is NULL in source — always None.
    """
    rows = con.execute(
        "SELECT id, designation, designation_i18n_json FROM design_groups"
    ).fetchall()
    return [
        {
            "id": row["id"],
            "designation": row["designation"],
            "designation_i18n_json": None,  # not populated in source
        }
        for row in rows
    ]


# ---------------------------------------------------------------------------
# build_mint
# ---------------------------------------------------------------------------

def build_mint(con: sqlite3.Connection) -> list[dict[str, Any]]:
    """Source: mints (29 rows).

    Target columns: id, country, mark, city, display_name
    Drops: founded_year, notes, created_at
    """
    rows = con.execute(
        "SELECT id, country, mark, city, display_name FROM mints"
    ).fetchall()
    return [
        {
            "id": row["id"],
            "country": row["country"],
            "mark": row["mark"],
            "city": row["city"],
            "display_name": row["display_name"],
        }
        for row in rows
    ]


# ---------------------------------------------------------------------------
# build_coin_mint_release
# ---------------------------------------------------------------------------

def build_coin_mint_release(con: sqlite3.Connection) -> list[dict[str, Any]]:
    """Source: coin_mint_releases LEFT JOIN mint_release_observations (3312 rows).

    mintage is not a column on coin_mint_releases; it is stored as a
    mint_release_observations row with fact_type='mintage' and value_json
    holding a bare integer string (e.g. '56695000').  3246 releases have a
    mintage observation; the remaining 66 get NULL.

    When multiple mintage observations exist for the same release (source
    conflicts), the highest value is used as the canonical figure.

    Target columns: id, parent_type_id, mint_year, mint_id, issue_type, mintage
    Drops: notes, created_at, updated_at
    """
    rows = con.execute(
        """
        SELECT
            cmr.id,
            cmr.parent_type_id,
            cmr.mint_year,
            cmr.mint_id,
            cmr.issue_type,
            MAX(CAST(mro.value_json AS INTEGER)) AS mintage
        FROM coin_mint_releases cmr
        LEFT JOIN mint_release_observations mro
               ON mro.mint_release_id = cmr.id
              AND mro.fact_type = 'mintage'
        GROUP BY cmr.id, cmr.parent_type_id, cmr.mint_year, cmr.mint_id, cmr.issue_type
        """
    ).fetchall()
    return [
        {
            "id": row["id"],
            "parent_type_id": row["parent_type_id"],
            "mint_year": row["mint_year"],
            "mint_id": row["mint_id"],
            "issue_type": row["issue_type"],
            "mintage": row["mintage"],  # int or None
        }
        for row in rows
    ]


# ---------------------------------------------------------------------------
# build_coin_credit
# ---------------------------------------------------------------------------

def build_coin_credit(con: sqlite3.Connection) -> list[dict[str, Any]]:
    """Source: coin_credits (1350 rows, PK = eurio_id, role, name).

    Target columns: eurio_id, role, name, position
    Drops: source, source_ref
    id is identity-generated by Postgres — omit.
    """
    rows = con.execute(
        "SELECT DISTINCT eurio_id, role, name, position FROM coin_credits"
    ).fetchall()
    return [
        {
            "eurio_id": row["eurio_id"],
            "role": row["role"],
            "name": row["name"],
            "position": row["position"],
        }
        for row in rows
    ]


# ---------------------------------------------------------------------------
# build_coin_topic
# ---------------------------------------------------------------------------

def build_coin_topic(con: sqlite3.Connection) -> list[dict[str, Any]]:
    """Source: coin_topics (1795 rows).

    The table allows multiple distinct topics per (eurio_id, lang) — each
    triple (eurio_id, lang, topic) is a separate row in the target.  Exact
    duplicate triples are collapsed with DISTINCT.

    Target columns: eurio_id, lang, topic
    Drops: source, confidence, method, model, fetched_at
    id is identity-generated by Postgres — omit.
    """
    rows = con.execute(
        "SELECT DISTINCT eurio_id, lang, topic FROM coin_topics"
    ).fetchall()
    return [
        {
            "eurio_id": row["eurio_id"],
            "lang": row["lang"],
            "topic": row["topic"],
        }
        for row in rows
    ]


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    from pathlib import Path

    _ML_ROOT = Path(__file__).resolve().parents[3]
    sys.path.insert(0, str(_ML_ROOT))

    from export.app_export.io import get_sqlite_con

    con = get_sqlite_con()

    builders = [
        ("design_group",      build_design_group),
        ("mint",              build_mint),
        ("coin_mint_release", build_coin_mint_release),
        ("coin_credit",       build_coin_credit),
        ("coin_topic",        build_coin_topic),
    ]

    for name, fn in builders:
        rows = fn(con)
        print(f"build_{name}: {len(rows)} rows")
        if rows:
            print(f"  sample keys : {list(rows[0].keys())}")
            print(f"  sample[0]   : {dict(rows[0])}")

    con.close()
