<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useCollectionStore } from '@/stores/collection'
const router = useRouter(); const store = useCollectionStore()
function onClick(e: MouseEvent) {
  const a = (e.target as HTMLElement).closest('[data-action]')?.getAttribute('data-action')
  if (a === 'next') router.push('/onboarding/2')
  else if (a === 'skip') { store.completeOnboarding(); router.push('/scan') }
}
</script>

<template>
<section @click="onClick" class="onboarding-1-root" data-scene="onboarding-1">
  <header class="onboarding-1-topbar">
    <div class="onboarding-1-brand">Eur<em>io</em></div>
    <button type="button" class="onboarding-1-skip" data-action="skip">Passer</button>
  </header>

  <div class="onboarding-1-stage">
    <div class="onboarding-1-coin-halo" aria-hidden="true"></div>
    <svg class="onboarding-1-coin" viewBox="0 0 240 240" aria-label="Pièce 2 euros générique">
      <defs>
        <radialGradient id="ob1-metal" cx="35%" cy="32%" r="75%">
          <stop offset="0%"  style="stop-color:var(--gold-soft)"/>
          <stop offset="35%" style="stop-color:var(--gold-300)"/>
          <stop offset="70%" style="stop-color:var(--gold)"/>
          <stop offset="100%" style="stop-color:var(--gold-deep)"/>
        </radialGradient>
        <radialGradient id="ob1-core" cx="40%" cy="35%" r="70%">
          <stop offset="0%"  style="stop-color:var(--gold-300)"/>
          <stop offset="100%" style="stop-color:var(--gold-700)"/>
        </radialGradient>
      </defs>
      <!-- outer ring -->
      <circle cx="120" cy="120" r="116" fill="url(#ob1-metal)"/>
      <circle cx="120" cy="120" r="116" fill="none" stroke="rgba(255,230,170,0.45)" stroke-width="1"/>
      <!-- inner disc -->
      <circle cx="120" cy="120" r="80" fill="url(#ob1-core)"/>
      <circle cx="120" cy="120" r="80" fill="none" stroke="rgba(143,118,55,0.55)" stroke-width="1"/>
      <!-- 12 euro stars on the outer ring -->
      <g style="fill:var(--surface)" opacity="0.92">
        <!-- Generated by hand : 12 points on r=98 around cx=cy=120 -->
        <g transform="translate(120 22)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(169 35.13)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(204.87 71)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(218 120)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(204.87 169)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(169 204.87)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(120 218)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(71 204.87)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(35.13 169)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(22 120)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(35.13 71)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
        <g transform="translate(71 35.13)"><polygon points="0,-6 1.76,-1.85 6,-1.85 2.62,0.7 3.88,4.85 0,2.4 -3.88,4.85 -2.62,0.7 -6,-1.85 -1.76,-1.85"/></g>
      </g>
      <!-- "2 EURO" label -->
      <text x="120" y="138" text-anchor="middle"
            style="font-family:var(--font-display);fill:var(--ink-soft)"
            font-style="italic"
            font-size="54"
            font-weight="500"
            letter-spacing="-2">2</text>
      <text x="120" y="160" text-anchor="middle"
            style="font-family:var(--font-mono);fill:var(--gold-deep)"
            font-size="9"
            font-weight="600"
            letter-spacing="2">EURO</text>
    </svg>
  </div>

  <div class="onboarding-1-pager" aria-hidden="true">
    <span data-active="true"></span>
    <span></span>
    <span></span>
  </div>

  <div class="onboarding-1-copy">
    <span class="eyebrow">Étape 1 sur 3</span>
    <h1>Scanne la pièce que tu as en main.</h1>
    <p>Pointe ton téléphone, Eurio reconnaît la pièce en quelques dixièmes de seconde — 100&nbsp;% hors-ligne.</p>
  </div>

  <div class="onboarding-1-cta">
    <button type="button" class="btn btn-gold" data-action="next">
      <span>Commencer</span>
      <span aria-hidden="true">→</span>
    </button>
    <div class="onboarding-1-legal">Fonctionne hors-ligne · Aucun compte requis</div>
  </div>
</section>
</template>

<style src="../../styles/onboarding-1.css"></style>
